/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.gui;

import com.example.dominio.Aplicaciones;
import com.example.dominio.Usuario;
import com.example.utils.Imagen;
import java.awt.Cursor;
import static java.awt.Frame.DEFAULT_CURSOR;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 *
 * @author Gonzalo
 */
public class jPListado extends javax.swing.JPanel {
   
    
    
    /**
     * Creates new form jPListado
     * @param a
     * @param editar bandera, en true edita, en false compra
     * @param u
     */
    public jPListado(Aplicaciones a, boolean editar, Usuario u) {
        
        initComponents();
        jpImagen.setSize(175, 180);
        Path pathImg = Paths.get("Aplicaciones/" + a.getNombreApp() + "/" + a.getImagen());

//        System.out.println("Aplicaciones/" + a.getNombreApp() + "/" + a.getImagen());
        if (Files.exists(pathImg)) {

                Imagen imagen = new Imagen(jpImagen.getHeight(),jpImagen.getWidth(),pathImg.toAbsolutePath().toString());
                
                jpImagen.add(imagen);
                jpImagen.repaint();
        }
        jLNombre.setText(a.getNombreApp());
        
        
        jLNombre.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if (editar)
                    new JDNvaApp(null, true, u, a).setVisible(true);
                else    
                    new JDComprarApp(null, true, a).setVisible(true);
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
                jLNombre.setCursor(new Cursor(HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
                jLNombre.setCursor(new Cursor(DEFAULT_CURSOR));
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLCalificacion = new javax.swing.JLabel();
        jpImagen = new javax.swing.JPanel();

        jLNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLNombre.setText("NombreApp");

        jLCalificacion.setText("Calificación");

        jpImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jpImagen.setPreferredSize(new java.awt.Dimension(175, 180));

        javax.swing.GroupLayout jpImagenLayout = new javax.swing.GroupLayout(jpImagen);
        jpImagen.setLayout(jpImagenLayout);
        jpImagenLayout.setHorizontalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        jpImagenLayout.setVerticalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCalificacion)
                    .addComponent(jLNombre)
                    .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCalificacion)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCalificacion;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JPanel jpImagen;
    // End of variables declaration//GEN-END:variables
}
